version: '3.4'

services:

  core:
    image: nexus.iex.ec/iexec-core:${CORE_VERSION}
    container_name: core
    environment:
    - IEXEC_CORE_WALLET_PATH=/iexec/wallet/encrypted-wallet.json
    - IEXEC_PRIVATE_CHAIN_ADDRESS=http://chain:8545
    - IEXEC_PUBLIC_CHAIN_ADDRESS=http://chain:8545
    - MONGO_HOST=mongo
    - IEXEC_IPFS_HOST=ipfs
    - IEXEC_SMS_HOST=sms
    - IEXEC_SCONE_CAS_HOST=iexec-cas
    volumes:
      - ./wallet/encrypted-wallet_scheduler.json:/iexec/wallet/encrypted-wallet.json
    ports:
    - 18090:18090
    restart: on-failure
    depends_on:
      - mongo
      - chain
      - ipfs
      - sms

  chain:
    image: nexus.iex.ec/poco-chain:${CHAIN_VERSION}
    container_name: chain
    ports:
      - 8545:8545

  mongo:
    image: mongo:4-xenial
    container_name: mongo
    ports:
      - 27017:27017

  mongo_ui:
    image: mongo-express:0.49
    container_name: mongo_ui
    environment:
    - ME_CONFIG_BASICAUTH_USERNAME=admin
    - ME_CONFIG_BASICAUTH_PASSWORD=y0urpassw00rd
    ports:
    - 8081:8081
    depends_on:
      - mongo

  ipfs:
    image: ipfs/go-ipfs:v0.4.20
    container_name: ipfs
    ports:
      - 8080:8080
      - 4001:4001
      - 5001:5001
    volumes:
      - /tmp/ipfs-docker-staging:/export
      - /tmp/ipfs-docker-data:/data/ipfs
    restart: on-failure

  sms:
    image: nexus.iex.ec/sms:latest
    container_name: sms
    environment:
      - HUB=0x60E25C038D70A15364DAc11A042DB1dD7A2cccBC
      - GATEWAY=http://chain:8545
    ports:
      - 5000:5000
    depends_on:
      - chain

  iexec-cas:
    image: nexus.iex.ec/iexec-cas:${IEXEC_CAS_VERSION}
    container_name: iexec-cas
    ports:
      - 18765:18765
    networks:
      - iexec-net
    devices:
      - /dev/isgx
