spring:
  profiles:
    active: "prod"  # "prod" profile should be loaded by default.
  data:
    mongodb:
      auto-index-creation: true # Auto-index creation is disabled by default starting with Spring Data MongoDB 3.x.
mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - com.iexec.core.configuration

cron:
  # all in milliseconds
  deal.replay: 60000  # 1m
  detector:
    worker-lost:      30000  # 30s
    chain:
      unstarted-tx:   300000  # 5m
      initialize:     30000   # 30s
      contribute:     30000   # 30s
      reveal:         30000   # 30s
      finalize:       30000   # 30s
      final-deadline: 30000   # 30s
    timeout:
      contribute:     120000  # 2m
      reveal: ${REVEAL_TIMEOUT_PERIOD:120000}  # 2m
      result-upload:  30000   # 30s

springdoc:
  packagesToScan: com.iexec.core
  pathsToMatch: /**
